container:
  image: python:3

test_task:
  env:
    - CODECOV_TOKEN: ENCRYPTED[73e0674b702504296fc4609d7be239ad6c06b7b380ad6fd1810baedba1f1fa7654638d0ea87ead8cc98a46a92d671f93]
  apt_setup_script:
    - apt-get update
    - |
      apt-get install -y \
      libnss-db \
      libdb-dev \
      libcurl4-gnutls-dev \
      libgnutls28-dev \
      libldap2-dev \
      libsasl2-dev
  pip_setup_script: pip install -r requirements.txt
  test_script: python setup.py test --addopts "-v --durations=0 --junitxml=test-results/junit.xml --cov=nss_cache"
  always:
    junit_result_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
      type: text/xml
  coverage_script:
    - pip install codecov
    - codecov

slapd_regtest_task:
  depends_on:
    - test
  allow_failures: true
  setup_script:
    - apt-get update
    - apt-get install -y slapd ldap-utils libnss-db db-util
  slapd_regtest_script:
    - tests/slapd-regtest

yapf_task:
  only_if: "changesInclude('setup.cfg', '**/*.py')"
  setup_script: pip install yapf
  yapf_script: yapf --diff --recursive nss_cache nsscache

pylint_task:
  only_if: "changesInclude('setup.cfg', '**/*.py')"
  setup_script: pip install pylint
  allow_failures: true
  pylint_script: pylint nsscache nss_cache
