version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor:
      name: "python/default"
      tag: "3.7"
    steps:
      - checkout
      # Install C libraries before pip install.
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      - python/load-cache
      - python/install-deps
      # CI-only deps, not in requirements.txt
      # TODO() remove coverage pinning when https://github.com/z4r/python-coveralls/issues/73 fixed.
      # pip can't install multiple packages if there's a dependency between some: https://github.com/pypa/pip/issues/1386
      - run: |
          pip install --user python-coveralls yapf pylint
          pip install --user coverage==4.5.4
      - run: export PATH=$PATH:$(python -m site --user-base)/bin
      - python/save-cache
      - run: python setup.py test --addopts "-v --durations=0 --junitxml=test-results/junit.xml --cov=nss_cache --cov-report term-missing --cov-report html"
      - run:
          command: |
            ls -al ~/.local/bin
            echo $PATH
            coveralls
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: htmlcov
      - run: pip install --user .
      - run: sudo apt install -y slapd ldap-utils libnss-db db-util
      - run: debian/tests/regtest
      - run:
          command: yapf --diff --recursive nss_cache nsscache
          no_output_timeout: 20m
      - run: pylint nsscache nss_cache || true

workflows:
  version: 2
  build:
    jobs:
      - build
